with open('/opt/hongloumeng/app/static/script.js') as f:
    js = f.read()

old = 'function loadSessions() { /* sidebar removed */ }\n\nfunction newChatSession() { /* sidebar removed */ }\n\nfunction switchSession(sid) { /* sidebar removed */ }\n\nfunction startRename(sid, currentTitle) { /* sidebar removed */ }\n\nfunction deleteSession(sid) { /* sidebar removed */ }\n\nfunction toggleSidebar() { /* sidebar removed */ }\n\n// Helper: add a session item to the sidebar immediately\nfunction _addSessionToSidebar(title) { /* sidebar removed */ }'

new = (
    'function loadSessions() {\n'
    '    var list = document.getElementById(\'sidebar-sessions\');\n'
    '    if (!list) return;\n'
    '    list.innerHTML = \'<div class="sidebar-loading">加载中……</div>\';\n'
    '    fetch(\'/api/chat/sessions\')\n'
    '        .then(function(r) { return r.json(); })\n'
    '        .then(function(data) {\n'
    '            if (!data.sessions || data.sessions.length === 0) {\n'
    '                list.innerHTML = \'<div class="sidebar-empty">暂无对话</div>\';\n'
    '                return;\n'
    '            }\n'
    '            var html = \'\';\n'
    '            data.sessions.forEach(function(s) {\n'
    '                var active = (s.id === window._chatSessionId) ? \' active\' : \'\';\n'
    '                html += \'<div class="sidebar-session-item\' + active + \'" data-sid="\' + s.id + \'">\'\n'
    '                    + \'<span class="sidebar-session-title" onclick="switchSession(\\\'\' + s.id + \'\\\')">\' + escapeHtml(s.title) + \'</span>\'\n'
    '                    + \'<span class="sidebar-session-rename"><input type="text" value="\' + escapeHtml(s.title) + \'" onblur="var v=this.value.trim();if(v)fetch(\\\'/api/chat/sessions/\' + s.id + \'\\\',{method:\\\'PATCH\\\',headers:{\\\'Content-Type\\\':\\\'application/json\\\'},body:JSON.stringify({title:v})}).then(function(){loadSessions()});else loadSessions();" onkeydown="if(event.key===\\\'Enter\\\')this.blur();"></span>\'\n'
    '                    + \'<button class="sidebar-session-del" onclick="event.stopPropagation();deleteSession(\\\'\' + s.id + \'\\\')" title="删除">✕</button>\'\n'
    '                    + \'</div>\';\n'
    '            });\n'
    '            list.innerHTML = html;\n'
    '        })\n'
    '        .catch(function() {\n'
    '            list.innerHTML = \'<div class="sidebar-empty">加载失败</div>\';\n'
    '        });\n'
    '}\n'
    '\n'
    'function newChatSession() {\n'
    '    fetch(\'/api/chat/sessions\', {\n'
    '        method: \'POST\',\n'
    '        headers: { \'Content-Type\': \'application/json\' },\n'
    '        body: JSON.stringify({ title: \'新对话\' }),\n'
    '    })\n'
    '    .then(function(r) { return r.json(); })\n'
    '    .then(function(data) {\n'
    '        if (data.session_id) {\n'
    '            window._chatSessionId = data.session_id;\n'
    '            localStorage.setItem(\'hlm_chat_session\', data.session_id);\n'
    '            window._chatMessages = [];\n'
    '            var chatMessages = document.getElementById(\'chat-messages\');\n'
    '            if (chatMessages) {\n'
    '                chatMessages.innerHTML = \'\';\n'
    '                addChatBubble(\'ai\', \'您好！我是红楼梦研究助手。您可以问我任何关于《红楼梦》的问题——原著情节、人物分析、版本源流、红学史论争等。我会以学术论文风格回答，并提供详细的文献出处。\');\n'
    '            }\n'
    '            loadSessions();\n'
    '        }\n'
    '    })\n'
    '    .catch(function(){});\n'
    '}\n'
    '\n'
    'function switchSession(sid) {\n'
    '    if (sid === window._chatSessionId) return;\n'
    '    window._chatSessionId = sid;\n'
    '    localStorage.setItem(\'hlm_chat_session\', sid);\n'
    '    fetch(\'/api/chat/sessions/\' + encodeURIComponent(sid) + \'/messages\')\n'
    '        .then(function(r) { return r.json(); })\n'
    '        .then(function(data) {\n'
    '            window._chatMessages = data.messages || [];\n'
    '            var chatMessages = document.getElementById(\'chat-messages\');\n'
    '            if (chatMessages) {\n'
    '                chatMessages.innerHTML = \'\';\n'
    '                (data.messages || []).forEach(function(m) {\n'
    '                    addChatBubble(m.role, m.content);\n'
    '                });\n'
    '                if (!data.messages || data.messages.length === 0) {\n'
    '                    addChatBubble(\'ai\', \'您好！我是红楼梦研究助手。您可以问我任何关于《红楼梦》的问题——原著情节、人物分析、版本源流、红学史论争等。我会以学术论文风格回答，并提供详细的文献出处。\');\n'
    '                }\n'
    '            }\n'
    '            loadSessions();\n'
    '        })\n'
    '        .catch(function(){});\n'
    '}\n'
    '\n'
    'function startRename(sid, currentTitle) {\n'
    '    var items = document.querySelectorAll(\'.sidebar-session-item\');\n'
    '    items.forEach(function(item) {\n'
    '        if (item.dataset.sid === sid) {\n'
    '            item.classList.add(\'renaming\');\n'
    '            var inp = item.querySelector(\'.sidebar-session-rename input\');\n'
    '            if (inp) {\n'
    '                inp.value = currentTitle;\n'
    '                inp.focus();\n'
    '                inp.select();\n'
    '            }\n'
    '        } else {\n'
    '            item.classList.remove(\'renaming\');\n'
    '        }\n'
    '    });\n'
    '}\n'
    '\n'
    'function deleteSession(sid) {\n'
    '    if (!confirm(\'确定删除此对话？\')) return;\n'
    '    fetch(\'/api/chat/sessions/\' + encodeURIComponent(sid), { method: \'DELETE\' })\n'
    '        .then(function() {\n'
    '            if (window._chatSessionId === sid) {\n'
    '                window._chatSessionId = \'\';\n'
    '                localStorage.removeItem(\'hlm_chat_session\');\n'
    '                window._chatMessages = [];\n'
    '                var chatMessages = document.getElementById(\'chat-messages\');\n'
    '                if (chatMessages) {\n'
    '                    chatMessages.innerHTML = \'\';\n'
    '                    addChatBubble(\'ai\', \'您好！我是红楼梦研究助手。您可以问我任何关于《红楼梦》的问题——原著情节、人物分析、版本源流、红学史论争等。我会以学术论文风格回答，并提供详细的文献出处。\');\n'
    '                }\n'
    '            }\n'
    '            loadSessions();\n'
    '        })\n'
    '        .catch(function(){});\n'
    '}\n'
    '\n'
    'function toggleSidebar() {\n'
    '    var sidebar = document.getElementById(\'index-sidebar\');\n'
    '    var main = document.querySelector(\'.main\');\n'
    '    if (!sidebar) return;\n'
    '    var collapsed = sidebar.classList.toggle(\'collapsed\');\n'
    '    if (main) main.classList.toggle(\'sidebar-collapsed\', collapsed);\n'
    '    var btn = sidebar.querySelector(\'.sidebar-toggle-btn\');\n'
    '    if (btn) btn.textContent = collapsed ? \'▶\' : \'◀\';\n'
    '    localStorage.setItem(\'hlm_sidebar_collapsed\', collapsed ? \'1\' : \'\');\n'
    '}\n'
    '\n'
    'function _addSessionToSidebar(title) {\n'
    '    loadSessions();\n'
    '}\n'
    '\n'
    '// --- Sidebar drag-to-resize ---\n'
    '(function() {\n'
    '    var handle = document.getElementById(\'sidebar-handle\');\n'
    '    var sidebar = document.getElementById(\'index-sidebar\');\n'
    '    var main = document.querySelector(\'.main\');\n'
    '    if (!handle || !sidebar) return;\n'
    '\n'
    '    var savedWidth = localStorage.getItem(\'hlm_sidebar_width\');\n'
    '    if (savedWidth) {\n'
    '        sidebar.style.width = savedWidth + \'px\';\n'
    '        handle.style.left = savedWidth + \'px\';\n'
    '    }\n'
    '\n'
    '    var isDragging = false;\n'
    '\n'
    '    handle.addEventListener(\'mousedown\', function(e) {\n'
    '        e.preventDefault();\n'
    '        isDragging = true;\n'
    '        handle.classList.add(\'active\');\n'
    '        document.body.style.cursor = \'col-resize\';\n'
    '        document.body.style.userSelect = \'none\';\n'
    '    });\n'
    '\n'
    '    document.addEventListener(\'mousemove\', function(e) {\n'
    '        if (!isDragging) return;\n'
    '        var w = Math.max(180, Math.min(500, e.clientX));\n'
    '        sidebar.style.width = w + \'px\';\n'
    '        handle.style.left = w + \'px\';\n'
    '        if (main) main.style.paddingLeft = (w + 18) + \'px\';\n'
    '    });\n'
    '\n'
    '    document.addEventListener(\'mouseup\', function() {\n'
    '        if (!isDragging) return;\n'
    '        isDragging = false;\n'
    '        handle.classList.remove(\'active\');\n'
    '        document.body.style.cursor = \'\';\n'
    '        document.body.style.userSelect = \'\';\n'
    '        var w = parseInt(sidebar.style.width, 10);\n'
    '        if (w > 0) localStorage.setItem(\'hlm_sidebar_width\', w);\n'
    '    });\n'
    '})();'
)

if old in js:
    js = js.replace(old, new)
    with open('/opt/hongloumeng/app/static/script.js', 'w') as f:
        f.write(js)
    print('DONE')
else:
    print('ERROR: stub functions not found')
